### ISSUE TITLE
WRT1900ACS V2 5ghz not working on McDebian 4.7.5 and 4.8.15

### ISSUE THREAD

**Issue by con7** [Chadster766/McDebian#22] opened 2016-12-06 18:41 UTC
Hi!

I'm running McDebian 4.7.5 on my WRT1900ACSv2 (EU version), but i can't get the 5ghz wifi to work.

I've tried different country codes, channels etc. but i always get this error:

```
root@MCDEBIAN:/etc/hostapd# hostapd /etc/hostapd/wlan0.conf 
Configuration file: /etc/hostapd/wlan0.conf
rfkill: Cannot open RFKILL control device
wlan0: interface state UNINITIALIZED->COUNTRY_UPDATE
wlan0: IEEE 802.11 Configured channel (40) not found from the channel list of current mode (2) IEEE 802.11a
wlan0: IEEE 802.11 Hardware does not support configured channel
Could not select hw_mode and channel. (-3)
wlan0: interface state COUNTRY_UPDATE->DISABLED
wlan0: AP-DISABLED 
hostapd_free_hapd_data: Interface wlan0 wasn't started
```

A single time it worked, but some minutes later it didn't worked again with the same config, so i think it's not a config issue.

My current config:

```
country_code=AT
interface=wlan0
bridge=br0
driver=nl80211
ctrl_interface=/var/run/hostapd
ssid=test-5ghz
ignore_broadcast_ssid=0
hw_mode=a
channel=36
auth_algs=1
wmm_enabled=1
ieee80211n=1
ht_capab=[LDPC][HT40+][SHORT-GI-20][SHORT-GI-40]
ieee80211ac=1
ieee80211d=1
vht_capab=[RXLDPC][SHORT-GI-80][RX-STBC-1][SU-BEAMFORMER][SU-BEAMFORMEE][MAX-A-MPDU-LEN-EXP7][RX-ANTENNA-PATTERN][TX-ANTENNA-PATTERN]
vht_oper_chwidth=1
vht_oper_centr_freq_seg0_idx=42

wpa=2
wpa_passphrase=mcdebian123
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP
```

```
root@MCDEBIAN:~# cat /sys/kernel/debug/ieee80211/phy1/mwlwifi/device_pwrtbl

power table loaded from dts: no
firmware region code: 0x30
number of channel: 38
```

Any suggestions? Thanks!

**Comment by Chadster766** [comment] 2016-12-06 19:11
Remove line "ieee80211d=1" from wlan0.conf

**Comment by con7** [comment] 2016-12-06 19:12
Already tried that, but i get the same error.

**Comment by Chadster766** [comment] 2016-12-06 19:16
Test change country code to "country_code=US"

**Comment by ValCher1961** [comment] 2016-12-06 19:17
Hi!
You execute a command after the first run of the nucleus - "depmod -a", try this command and reboot.

**Comment by con7** [comment] 2016-12-06 19:37
thanks,
@Chadster766 already tried different country codes.. but it didn't help.
@ValCher1961 just tried that.. but after a reboot wlan0 doesn't come up.
Really strange.. no matter which settings i try, it just wont work.

**Comment by Chadster766** [comment] 2016-12-06 19:50
Try channel=40 with vht_oper_centr_freq_seg0_idx=46

**Comment by con7** [comment] 2016-12-06 20:19
Thanks, but already tried that.. i've just flashed McDebian 4.4.16 and 5ghz wifi is working out of the box.. maybe it's because of the newer mwlwifi driver?

**Comment by con7** [comment] 2016-12-06 20:23
I haven't changed wifi driver, i've just tested with stock mcdebian (4.7.5: not working, 4.4.16: working).

**Comment by Chadster766** [comment] 2016-12-06 20:29
Interesting, did you run all the upgrade scripts for the WRT1900AC ACS?

https://github.com/Chadster766/McDebian/wiki/X.-McDebian-Updates#installation-instructions-for-wrt1900ac-v2-wrt1900acs-and-wrt1200ac-from-a-live-mcdebian-router

**Comment by con7** [comment] 2016-12-06 20:52
Yes, I did. I'm currently running 4.4.16, will try 4.7.5 tomorrow again and report back. Thanks!

**Comment by con7** [comment] 2016-12-07 21:16
Just upgraded again from 4.4.16 to 4.7.5 - same problem, can't get 5ghz wifi to work, no matter which settings.
I will further try to find out what causes the problem.

**Comment by Chadster766** [comment] 2016-12-07 21:19
I recommend you wait a bit on troubleshooting this :smiley: 

Instead let me put together 4.8.12 update with the latest mwlwifi driver updates for you to try.

**Comment by con7** [comment] 2016-12-07 21:27
ok, thanks :D but i just found the issue.. the issue is the mwlwifi firmware at /lib/firmware/mwlwifi.
i replaced the fw-files with the files of 4.4.16, rebooted and wifi is now working without any problems.. i'll check with the latest firmware files in a few minutes..

**Comment by con7** [comment] 2016-12-07 21:34
As i thought.. with the latest mwlwifi firmware from the kaloz repo it doesn't work.

**Comment by con7** [comment] 2016-12-07 21:39
I'll wait for 4.8.12 update with the latest mwlwifi driver to check further. Thanks! ;)

**Comment by Chadster766** [comment] 2016-12-19 00:34
Please test McDebian v4.8.15 on your WRT1900ACS V2:

Commands to Upgrade a live McDebian v4.7.5 WRT1900ACS V2 or WRT1900AC V2 system to McDebian v4.8.15:

```
cd /
wget --user=mcdebian --password=mcdebian123 http://www.protechs-online.com/downloads/McDebian/firmwares/McDebian-WRT1900AC-V2-FW_VER1_kernel_4_8_15.img
wget --user=mcdebian --password=mcdebian123 http://www.protechs-online.com/downloads/McDebian/rootfs-updates/mcdebian-rootfs-update-v4_8_15.gz
tar zxf ./mcdebian-rootfs-update-v4_8_15.gz

#optional
rm -rf /mnt/usbkey/lib/modules/4.7.5
```

**Comment by Chadster766** [comment] 2016-12-19 04:38
I'm going to close this until I hear back from you :smile:

**Comment by jbsky** [comment] 2016-12-19 08:00
Hi @Chadster766,
Please, can you give a link of .config file?

**Comment by Chadster766** [comment] 2016-12-19 09:51
I will upload it to the repo tomorrow :smile:

**Comment by con7** [comment] 2016-12-19 17:41
Thanks! But same problem with the new 4.8.15 update and the newer mwlwifi firmware files. I think it's a V2 only related problem..

**Comment by Chadster766** [comment] 2016-12-19 21:30
Would you be willing to do a Skype discussion on this issue? 

Skype name: chad. mccue766

**Comment by con7** [comment] 2016-12-20 20:21
Yes sure, but i'm currently not at home. Will add you asap :)
Maybe it's because of the hostapd version? McDebian's hostapd version is 2.3, LEDE (for example) 2.6.

**Comment by Chadster766** [comment] 2016-12-20 20:26
Ok I'm on central time.

**Comment by JoinTheRealms** [comment] 2016-12-21 08:41
Hi there, I'd like to report this issue on the 1900v1 also, started after a recent apt upgrade.

It can't seem to set crda properly, iw reg set US runs without error but it remains unset. I get this error in journalctl: 

/sbin/crda terminated by signal 11 (segmentation fault) I'm on 4.7.5

**Comment by Chadster766** [comment] 2016-12-21 14:00
Downgrading hostapd and crda to Debian Sid packages is interesting and would provide you will a different available 5Ghz channels.

When the issue appeared did you do a general Jessie "apt-update" and then "apt-get upgrade" with the current McDebian apt sources or something else?

**Comment by Chadster766** [comment] 2016-12-21 19:36
Troubleshooting with @con7 has proven the issue exists on McDebian 4.7.5 and 4.8.15 :disappointed:

**Comment by JoinTheRealms** [comment] 2016-12-21 22:15
@Chadster766 it was just a general "apt update", "apt upgrade". I hadn't noticed the issue because I hadn't rebooted for a couple of days after.

**Comment by Chadster766** [comment] 2016-12-22 02:51
@JTRealms you should be able to extract the 4.8.15 update to get those kernel drivers back into operation.

**Comment by con7** [comment] 2016-12-22 21:12
Got the 5ghz wifi to work if i set "REGDOMAIN" in /etc/default/crda (in my case AT).
Then after a reboot hostapd starts without any problems.. but if i restart hostapd again, it isn't working anymore - it just works only directly after rebooting the device.

**Comment by Chadster766** [comment] 2016-12-22 21:23
Try making setting both crda and wlan0.conf to the same country code.

**Comment by con7** [comment] 2016-12-22 21:25
It is already the same country code.

**Comment by Chadster766** [comment] 2016-12-22 21:44
In your testing have you tried a clean rootfs with no apt-get upgrades?

**Comment by con7** [comment] 2016-12-22 22:02
Yes, i tested without any upgrades.

**Comment by Chadster766** [comment] 2016-12-22 22:07
Ok thanks for the update :smile:

**Comment by con7** [comment] 2016-12-22 22:16
One more thing i've just found out:
If i debug the communication between the kernel and udev i see country code changes to "EU" every few seconds:

```
UDEV  [532.978056] change   /devices/platform/regulatory.0 (platform)
ACTION=change
COUNTRY=00
DEVPATH=/devices/platform/regulatory.0
MODALIAS=platform:regulatory
SEQNUM=2528
SUBSYSTEM=platform
USEC_INITIALIZED=2970300

UDEV  [532.984440] change   /devices/platform/regulatory.0 (platform)
ACTION=change
COUNTRY=EU
DEVPATH=/devices/platform/regulatory.0
MODALIAS=platform:regulatory
SEQNUM=2529
SUBSYSTEM=platform
USEC_INITIALIZED=77448
```

Maybe this is the reason why it won't work after a hostapd restart. Because if i set the country-code to EU in /etc/default/crda and hostapd config, wifi wont work even after rebooting the device.

I'll try to find out more :)

**Comment by con7** [comment] 2016-12-23 00:48
Ok, the cause of the problem is crda.
crda tries to set country to EU but the regulatory.bin in /lib/crda doesn't have country_code "EU".

```
root@MCDEBIAN:/lib/crda# regdbdump regulatory.bin | grep EU
root@MCDEBIAN:/lib/crda#
```

I've added EU to db.txt and generated my own regulatory.bin, now it is working without any problems (no matter if I set EU or AT in /etc/default/crda and hostapd config).
But I don't know why crda want's implicitly to set country to EU.

I think everything would work if using static regulatory database (CONFIG_CFG80211_INTERNAL_REGDB) instead of crda, but that is not a solution of the cause.

**Comment by Chadster766** [comment] 2016-12-23 04:37
Thanks a lot for your great troubleshooting. 

So will a newer crda db fix the issue?

**Comment by con7** [comment] 2016-12-23 11:27
A crda db with country_code "EU" would fix the issue, but EU is not a valid ISO 3166 country code, so the crda-db without EU is in point of fact correct (i believe)
I think the main problem is, that in my case crda want's to set country to EU, which should not happen.

**Comment by Chadster766** [comment] 2016-12-23 15:20
Great troubleshooting :smile: 

I should be able to reproduce the issue on my WRT3200ACM setting my wireless to a different country code than the driver.

The EU country code is an odd situation. I wonder why Marvell would hardcode a none standard country code into the firmware file or on chip. My guess is that Marvell must have provided a proprietary utility for that to OEM manufactures.

**Comment by con7** [comment] 2016-12-23 15:46
I'll open an issue at mwlwifi driver at github, maybe they would change region code mapping in driver - this is the relevant code:

https://github.com/kaloz/mwlwifi/blob/master/main.c

```
static const struct region_code_mapping regmap[] = {
	{"US", 0x10}, /* US FCC */
	{"CA", 0x20}, /* Canada */
	**{"EU", 0x30}, /* ETSI   */** <--
	{"ES", 0x31}, /* Spain  */
	{"FR", 0x32}, /* France */
	{"JP", 0x40}, /* Japan  */
	{"TW", 0x80}, /* Taiwan */
	{"AU", 0x81}, /* Australia */
	{"CN", 0x90}, /* China (Asia) */
};
```

All other country codes are valid.

**Comment by con7** [comment] 2016-12-23 15:56
Just found the same issue here with an other Marvell driver: https://patchwork.kernel.org/patch/7768381/ 😄

**Comment by con7** [comment] 2016-12-23 16:07
Opened new issue at mwlwifi: https://github.com/kaloz/mwlwifi/issues/130

**Comment by Chadster766** [comment] 2016-12-23 16:24
Excellent I hope it can be changed to a valid country code otherwise we can customise the crda db

**Comment by Chadster766** [comment] 2016-12-24 02:19
Sorry I mean we can customize mwlwifi

**Comment by con7** [comment] 2016-12-25 22:40
Thanks @Chadster766. Already recompiled mwlwifi with an valid country code for 0x30 and wifi is working perfectly for me now.
We will see if it will be changed in mwlwifi repo too, but for now everything is fine 👍

**Comment by Chadster766** [comment] 2016-12-27 01:41
@con7 can you test a new beta for me? 

It has EU added to the crda database, basically a copy of FR which should allow you to run an unmodified mwlwifi module.

The update also includes WRT3200 driver and firmware for it's 3rd radio. The udev script has been modified to work with the WRT3200 as well.

If it runs on your WRT1900ACM V2 then that would confirm the udev script for me.

```
wget --user=mcdebian --password=mcdebian123 http://www.protechs-online.com/downloads/McDebian/firmwares/McDebian-WRT1900AC-V2-FW_VER2_kernel_4_8_15.img
```

```
wget --user=mcdebian --password=mcdebian123 http://www.protechs-online.com/downloads/McDebian/rootfs-updates/mcdebian-rootfs-update-v4_8_15-VER2.gz
```

**Comment by con7** [comment] 2016-12-27 13:30
@Chadster766 I've just tested it and everything works 👍

**Comment by Chadster766** [comment] 2016-12-27 15:31
Thanks so much :smile:

**Comment by lantis1008** [comment] 2016-12-28 21:51
What functionality do you hope to get out of the Bluetooth module? The same as in OEM? Or can we use it as a standalone Bluetooth?

**Comment by Chadster766** [comment] 2016-12-28 22:03
@lantis1008 the WRT3200ACM has a 3rd Dual Band AC Radio. I tested the mwifiex driver for this radio and it works fine.

The 3rd radio could be used for all kinds of things.

**Comment by lantis1008** [comment] 2016-12-28 22:24
Hmm. On the FCC submission I thought the third band was a Bluetooth module
https://fccid.io/document.php?id=3085326

**Comment by Chadster766** [comment] 2016-12-28 22:36
Ya I don't quite get it either but it is what it is :smile:

**Comment by lantis1008** [comment] 2016-12-28 22:43
Sounds good to me lol

**Comment by Chadster766** [comment] 2016-12-29 17:19
This was resolved by adding the "EU" country code to the CRDA database in McDebian update v4.8.15-VER3.

**Closed by Chadster766** 2016-12-29 17:19 UTC

**Comment by lantis1008** [comment] 2017-01-30 11:06
@Chadster766
Any clues on changing the region the device is hardcoded for?
I've received a US device in Australia and would like to switch it to AU 0x81. 
Yuharlin at mwlwifi repo was unable to help and neither was linksys support (who didn't even appear to understand the question)

Is the powertable itself hardcoded on the device as wel or does this get pulled from CRDA? If so I could set the US region to mimic AU, although this isn't my ideal solution. 

I apologise that this isn't specifically a McDebian question.

**Comment by Chadster766** [comment] 2017-01-30 18:41
I believe the country code and power tables are hardcoded but I don't know where. CRDA isn't used because the driver detects the country code somewhere and overrides the settings in the driver. The hostapd.conf files must match this country code to work.
